"""Tabels creation

Revision ID: c6fa0f1ff507
Revises: 
Create Date: 2023-07-08 20:44:14.625935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fa0f1ff507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_10_2',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('entalpia_0_98', sa.DECIMAL(), nullable=True),
    sa.Column('moisture_content', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_11_1_1',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('I', sa.DECIMAL(), nullable=True),
    sa.Column('II', sa.DECIMAL(), nullable=True),
    sa.Column('III', sa.DECIMAL(), nullable=True),
    sa.Column('IV', sa.DECIMAL(), nullable=True),
    sa.Column('V', sa.DECIMAL(), nullable=True),
    sa.Column('VI', sa.DECIMAL(), nullable=True),
    sa.Column('VII', sa.DECIMAL(), nullable=True),
    sa.Column('VIII', sa.DECIMAL(), nullable=True),
    sa.Column('IX', sa.DECIMAL(), nullable=True),
    sa.Column('X', sa.DECIMAL(), nullable=True),
    sa.Column('XI', sa.DECIMAL(), nullable=True),
    sa.Column('XII', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_11_1_2',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('I', sa.DECIMAL(), nullable=True),
    sa.Column('II', sa.DECIMAL(), nullable=True),
    sa.Column('III', sa.DECIMAL(), nullable=True),
    sa.Column('IV', sa.DECIMAL(), nullable=True),
    sa.Column('V', sa.DECIMAL(), nullable=True),
    sa.Column('VI', sa.DECIMAL(), nullable=True),
    sa.Column('VII', sa.DECIMAL(), nullable=True),
    sa.Column('VIII', sa.DECIMAL(), nullable=True),
    sa.Column('IX', sa.DECIMAL(), nullable=True),
    sa.Column('X', sa.DECIMAL(), nullable=True),
    sa.Column('XI', sa.DECIMAL(), nullable=True),
    sa.Column('XII', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_13_1',
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('I', sa.DECIMAL(), nullable=True),
    sa.Column('II', sa.DECIMAL(), nullable=True),
    sa.Column('III', sa.DECIMAL(), nullable=True),
    sa.Column('IV', sa.DECIMAL(), nullable=True),
    sa.Column('V', sa.DECIMAL(), nullable=True),
    sa.Column('VI', sa.DECIMAL(), nullable=True),
    sa.Column('VII', sa.DECIMAL(), nullable=True),
    sa.Column('VIII', sa.DECIMAL(), nullable=True),
    sa.Column('IX', sa.DECIMAL(), nullable=True),
    sa.Column('X', sa.DECIMAL(), nullable=True),
    sa.Column('XI', sa.DECIMAL(), nullable=True),
    sa.Column('XII', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('latitude')
    )
    op.create_table('table_3_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('cold_temperature_1day_0.98', sa.Integer(), nullable=True),
    sa.Column('cold_temperature_1day_0.92', sa.Integer(), nullable=True),
    sa.Column('cold_temperature_5day_0.98', sa.Integer(), nullable=True),
    sa.Column('cold_temperature_5day_0.92', sa.Integer(), nullable=True),
    sa.Column('temperature_0.94', sa.Integer(), nullable=True),
    sa.Column('absolutely_minimal_temperature', sa.Integer(), nullable=True),
    sa.Column('mean_1day_amplitude_the_coldest_month', sa.DECIMAL(), nullable=True),
    sa.Column('duration_of_period_with_mean_1day_temperature_1', sa.Integer(), nullable=True),
    sa.Column('mean_temperature_1', sa.DECIMAL(), nullable=True),
    sa.Column('duration_of_period_with_mean_1day_temperature_2', sa.Integer(), nullable=True),
    sa.Column('mean_temperature_2', sa.DECIMAL(), nullable=True),
    sa.Column('duration_of_period_with_mean_1day_temperature_3', sa.Integer(), nullable=True),
    sa.Column('mean_temperature_3', sa.DECIMAL(), nullable=True),
    sa.Column('mean_monthly_relative_moisture_the_coldest_month', sa.Integer(), nullable=True),
    sa.Column('mean_monthly_relative_moisture_in15oclock_the_coldest_month', sa.Integer(), nullable=True),
    sa.Column('precipitation_november-march_mm', sa.Integer(), nullable=True),
    sa.Column('dominant_wind_direction_december-february', sa.String(), nullable=True),
    sa.Column('maximal_of_mean_speed_wind_by_point_january', sa.DECIMAL(), nullable=True),
    sa.Column('mean_wind_speed_in_period_of_mean_1day_temperature', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_4_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('pressure', sa.DECIMAL(), nullable=True),
    sa.Column('temperature_095', sa.Integer(), nullable=True),
    sa.Column('temperature_098', sa.Integer(), nullable=True),
    sa.Column('mean_maximal_month_temperature', sa.DECIMAL(), nullable=True),
    sa.Column('absolutely_maximal_temperature', sa.Integer(), nullable=True),
    sa.Column('mean_daily_amplitude_temperature_the_warmest_month', sa.DECIMAL(), nullable=True),
    sa.Column('mean_monthly_relative_humidity_the_warmest_month', sa.Integer(), nullable=True),
    sa.Column('mean_monthly_relative_humidity_the_warmest_month_15h', sa.Integer(), nullable=True),
    sa.Column('precipitation_amount_april_october', sa.Integer(), nullable=True),
    sa.Column('max_daily_precipitation_amount', sa.Integer(), nullable=True),
    sa.Column('dominant_wind_direction_june_august', sa.String(), nullable=True),
    sa.Column('minimal_of_mean_speed_wind_by_point_july', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_5_1',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('I', sa.DECIMAL(), nullable=True),
    sa.Column('II', sa.DECIMAL(), nullable=True),
    sa.Column('III', sa.DECIMAL(), nullable=True),
    sa.Column('IV', sa.DECIMAL(), nullable=True),
    sa.Column('V', sa.DECIMAL(), nullable=True),
    sa.Column('VI', sa.DECIMAL(), nullable=True),
    sa.Column('VII', sa.DECIMAL(), nullable=True),
    sa.Column('VIII', sa.DECIMAL(), nullable=True),
    sa.Column('IX', sa.DECIMAL(), nullable=True),
    sa.Column('X', sa.DECIMAL(), nullable=True),
    sa.Column('XI', sa.DECIMAL(), nullable=True),
    sa.Column('XII', sa.DECIMAL(), nullable=True),
    sa.Column('year', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_6_1',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('maximal_temperature_amplitude', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_7_1',
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('I', sa.DECIMAL(), nullable=True),
    sa.Column('II', sa.DECIMAL(), nullable=True),
    sa.Column('III', sa.DECIMAL(), nullable=True),
    sa.Column('IV', sa.DECIMAL(), nullable=True),
    sa.Column('V', sa.DECIMAL(), nullable=True),
    sa.Column('VI', sa.DECIMAL(), nullable=True),
    sa.Column('VII', sa.DECIMAL(), nullable=True),
    sa.Column('VIII', sa.DECIMAL(), nullable=True),
    sa.Column('IX', sa.DECIMAL(), nullable=True),
    sa.Column('X', sa.DECIMAL(), nullable=True),
    sa.Column('XI', sa.DECIMAL(), nullable=True),
    sa.Column('XII', sa.DECIMAL(), nullable=True),
    sa.Column('year', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('table_8_1',
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('N_40', sa.Integer(), nullable=True),
    sa.Column('N_44', sa.Integer(), nullable=True),
    sa.Column('N_48', sa.Integer(), nullable=True),
    sa.Column('N_52', sa.Integer(), nullable=True),
    sa.Column('N_56', sa.Integer(), nullable=True),
    sa.Column('N_60', sa.Integer(), nullable=True),
    sa.Column('N_64', sa.Integer(), nullable=True),
    sa.Column('N_68', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('table_9_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('N_40', sa.Integer(), nullable=True),
    sa.Column('N_44', sa.Integer(), nullable=True),
    sa.Column('N_48', sa.Integer(), nullable=True),
    sa.Column('N_52', sa.Integer(), nullable=True),
    sa.Column('N_56', sa.Integer(), nullable=True),
    sa.Column('N_60', sa.Integer(), nullable=True),
    sa.Column('N_64', sa.Integer(), nullable=True),
    sa.Column('N_68', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('table_9_1')
    op.drop_table('table_8_1')
    op.drop_table('table_7_1')
    op.drop_table('table_6_1')
    op.drop_table('table_5_1')
    op.drop_table('table_4_1')
    op.drop_table('table_3_1')
    op.drop_table('table_13_1')
    op.drop_table('table_11_1_2')
    op.drop_table('table_11_1_1')
    op.drop_table('table_10_2')
    # ### end Alembic commands ###
