version: "24.0.2"

services:
  db:
    image: postgres:15
    container_name: db_sp_app
    command: -p 2005
    expose:
      - 2005
    env_file:
      - .env-non-dev
    volumes:
      - ./sp_app/data:/data
    
  sp_app:
    build:
      context: ./sp_app/  
      dockerfile: ./Dockerfile
    env_file:
      - .env-non-dev
    container_name: sp_app
    command: ["/fastapi_app/sp_app.sh"]
    ports:
      - "8099:8000"
    depends_on:
      - db


  react:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    container_name: react_sp_app
    ports:
      - "3099:3000"
    depends_on:
      - sp_app
